WHITESPACE = _{ " " | "\t" | "\n" }

// Precedence: OR/NOR < XOR/XNOR < AND/NAND < NOT < primary
expr       = { or }

or         = { nor ~ ( "|"  ~ nor )* }
nor        = { xor ~ ( "!|" ~ xor )* }
xor        = { xnor ~ ( "^"  ~ xnor )* }
xnor       = { and ~ ( "!^" ~ and )* }
and        = { nand ~ ("&"  ~ nand )* }
nand       = { not ~ ("!&" ~ not )* }
not        = { ("'" | "!")* ~ primary }
primary    = { ident | "(" ~ expr ~ ")" }
ident      = @{ ASCII_ALPHANUMERIC+ }
